name: 'ci'
description: 'Executes Swift specific CI steps'
inputs:
  type:
    description: 'The type of CI step to run'
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'relay.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true

runs:
  using: "composite"
  steps:
    # - uses: actions/cache/restore@v3
    #   with:
    #     path: |
    #       products.tar
    #     key: ${{ runner.os }}-deriveddata-main-${{ inputs.commit-sha }}
    #     # FOR TESTING: remove restore key without `main` as we don't want to use cache from feature branches
    #     restore-keys: |
    #       ${{ runner.os }}-deriveddata-main-
    #       ${{ runner.os }}-deriveddata- 

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
          name: main-derivedData
          workflow: build_artifacts.yml
          repo: 'WalletConnect/WalletConnectSwiftV2'

    - name: Untar DerivedDataCache
      shell: bash
      run: tar xPpf products.tar

    - name: Run integration tests
      if: inputs.type == 'integration-tests'
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: make integration_tests RELAY_HOST=$RELAY_ENDPOINT PROJECT_ID=$PROJECT_ID

    - name: Run relay integration tests
      if: inputs.type == 'relay-tests'
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: make relay_tests RELAY_HOST=$RELAY_ENDPOINT PROJECT_ID=$PROJECT_ID

    - name: Run smoke tests
      if: inputs.type == 'smoke-tests'
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: make smoke_tests RELAY_HOST=$RELAY_ENDPOINT PROJECT_ID=$PROJECT_ID

    - name: Run unit tests
      if: inputs.type == 'unit-tests'
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: make unit_tests RELAY_HOST=$RELAY_ENDPOINT PROJECT_ID=$PROJECT_ID

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
          check_name: ${{ matrix.test-type }} junit report
          report_paths: 'test_results/report.junit'
       
    - name: Zip test artifacts
      if: always()
      shell: bash
      run: test -d "test_results" && zip artifacts.zip -r ./test_results || echo "Nothing to zip"

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.test-type }} test_results
        path: ./artifacts.zip
        if-no-files-found: warn