name: 'ci'
description: 'Executes Swift specific CI steps'
inputs:
  type:
    description: 'The type of CI step to run'
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'relay.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true

runs:
  using: "composite"
  steps:
    # Package builds
    - name: Run tests
      if: inputs.type == 'unit-tests'
      shell: bash
      run: "xcodebuild \
        -project Example/ExampleApp.xcodeproj \ 
        -scheme WalletConnect \
        -clonedSourcePackagesDirPath SourcePackagesCache \
        -destination 'platform=iOS Simulator,name=iPhone 13' \
        -derivedDataPath DerivedDataCache \
        test"

    # Integration tests
    - name: Run integration tests
      if: inputs.type == 'integration-tests'
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: "xcodebuild \
        -project Example/ExampleApp.xcodeproj \ 
        -scheme IntegrationTests \
        -clonedSourcePackagesDirPath SourcePackagesCache \
        -destination 'platform=iOS Simulator,name=iPhone 13' \
        -derivedDataPath DerivedDataCache \
        RELAY_HOST='$RELAY_ENDPOINT' \
        PROJECT_ID='$PROJECT_ID' \
        test"

    # Wallet build
    - name: Build Example Wallet
      if: inputs.type == 'build-example-wallet'
      shell: bash
      run: "xcodebuild \
       -project Example/ExampleApp.xcodeproj \
       -scheme Wallet \
       -clonedSourcePackagesDirPath SourcePackagesCache \
       -destination 'platform=iOS Simulator,name=iPhone 13' \
       -derivedDataPath DerivedDataCache"

    # DApp build
    - name: Build Example Dapp
      if: inputs.type == 'build-example-dapp'
      shell: bash
      run: "xcodebuild \
        -project Example/ExampleApp.xcodeproj \
        -scheme DApp \
        -clonedSourcePackagesDirPath SourcePackagesCache \
        -destination 'platform=iOS Simulator,name=iPhone 13' \
        -derivedDataPath DerivedDataCache"

    # UI tests
    - name: UI Tests
      if: inputs.type == 'ui-tests'
      shell: bash
      run: "xcodebuild \
        -project Example/ExampleApp.xcodeproj \
        -scheme UITests \
        -derivedDataPath DerivedDataCache \
        -clonedSourcePackagesDirPath SourcePackagesCache \
        -destination 'platform=iOS Simulator,name=iPhone 13' test"
      continue-on-error: true
