name: 'run_tests_without_building'
description: 'Executes specific Swift tests using prebuilt artifacts from build_artifacts.yml workflow from main branch'
inputs:
  type:
    description: 'The type of CI step to run'
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'relay.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
          name: main-derivedData
          workflow: build_artifacts.yml
          repo: 'WalletConnect/WalletConnectSwiftV2'

    - name: Untar DerivedDataCache
      shell: bash
      run: tar xPpf products.tar

    - name: Run tests
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
        TYPE: ${{ inputs.type }}
      run: make $TYPE RELAY_HOST=$RELAY_ENDPOINT PROJECT_ID=$PROJECT_ID

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
          check_name: ${{ inputs.type }} junit report
          report_paths: 'test_results/report.junit'
       
    - name: Zip test artifacts
      if: always()
      shell: bash
      run: test -d "test_results" && zip artifacts.zip -r ./test_results || echo "Nothing to zip"

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.type }} test_results
        path: ./artifacts.zip
        if-no-files-found: warn