name: build_artifacts

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
    relay-endpoint:
      description: 'The endpoint of the relay e.g. relay.walletconnect.com'
      required: false
      default: 'staging.relay.walletconnect.com'
    project-id:
      description: 'WalletConnect project id'
      required: true
    
  push:
    branches: [ main ]

jobs:
  build:    
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: |
          **/SourcePackagesCache
          DerivedDataCache
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build for testing
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: make build_all RELAY_HOST=$RELAY_ENDPOINT PROJECT_ID=$PROJECT_ID

    - name: Tar DerivedDataCache
      shell: bash
      run: test -d "DerivedDataCache" && tar cfPp products.tar --format posix DerivedDataCache/Build

    - uses: actions/upload-artifact@v3
      with:
        name: main-derivedData
        path: products.tar