name: build_artifacts

on:
  workflow_dispatch:
    
  push:
    branches: [ main ]

jobs:
  build:    
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: |
          **/SourcePackagesCache
          DerivedDataCache
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build for testing
      shell: bash
      run: make build_all RELAY_HOST=${{ inputs.project-id }} PROJECT_ID=${{ inputs.project-id }}

    - name: Tar DerivedDataCache
      shell: bash
      run: test -d "DerivedDataCache" && tar cfPp products.tar --format posix DerivedDataCache/Build

    - uses: actions/upload-artifact@v3
      with:
        name: main-derivedData
        path: products.tar