# This workflow sets the package version for user agent
# when pull request is to main is opened
# it takes pull request name and makes it a package version
# pull request name should always be a version of a new release

name: set-user-agent

on:
  pull_request:
    branches: [ main ]
env:
  PACKAGE_VERSION: ${{ github.event.pull_request.title }}

jobs:
  set-user-agent:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set User Agent
        shell: bash
        run: ./.github/scripts/set-user-agent.sh

      - uses: stefanzweifel/git-auto-commit-action@v4

